name: Deploy MkDocs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: python -m pip install -U pip
      - run: python -m pip install -U mkdocs mkdocs-material
      - run: mkdocs gh-deploy --force
